program: scripts/train.py
method: bayes
metric:
  name: val_accuracy
  goal: maximize
parameters:
  dataset:
    value: fashion_mnist
  data_source:
    value: keras
  hidden_layers:
    values:
      - [128, 64]
      - [256, 128]
      - [128, 128, 64]
  activation:
    values: [relu, tanh]
  optimizer:
    values: [adam, rmsprop, momentum]
  learning_rate:
    distribution: log_uniform
    min: -4.0
    max: -2.0
  batch_size:
    values: [32, 64, 128]
  epochs:
    value: 15
  weight_init:
    values: [he, xavier]
  l2_coeff:
    distribution: log_uniform
    min: -6.0
    max: -2.0
  wandb_mode:
    value: online
early_terminate:
  type: hyperband
  min_iter: 3
  max_iter: 15
